"""
main.py
=======
Application entrypoint. Creates the FastAPI app, wires up CORS, logging,
routers, and a couple of top-level endpoints (root + health check).

Run locally with:
    uvicorn app.main:app --reload --port 8000

Then open http://localhost:8000/docs for interactive API documentation
(automatically generated by FastAPI from the Pydantic schemas).
"""

import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import get_settings
from app.core.logging_config import configure_logging
from app.models.schemas import HealthResponse
from app.routers import review

settings = get_settings()
configure_logging(settings.ENVIRONMENT)
logger = logging.getLogger(__name__)

app = FastAPI(
    title=settings.APP_NAME,
    version=settings.APP_VERSION,
    description=(
        "An AI-powered code review API. Combines open-source static-analysis "
        "tools (Bandit, Pylint, Radon) with a pluggable, free/open-source LLM "
        "backend (Ollama by default) to surface bugs, security issues, "
        "performance problems, and best-practice violations."
    ),
)

# CORS: allow the React frontend (running on a different origin/port during
# development, or a different container in production) to call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[origin.strip() for origin in settings.CORS_ORIGINS.split(",") if origin.strip()],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(review.router)


@app.get("/", tags=["meta"], summary="Basic liveness message.")
async def root() -> dict:
    """A minimal endpoint confirming the API process is up and reachable."""
    return {"message": f"{settings.APP_NAME} is running.", "docs": "/docs"}


@app.get("/api/health", response_model=HealthResponse, tags=["meta"], summary="Health/readiness check.")
async def health_check() -> HealthResponse:
    """
    Report service status and which LLM provider is currently configured.

    Useful for Docker/Kubernetes health probes and for the frontend to show
    a "backend unreachable" banner instead of failing silently.
    """
    return HealthResponse(status="ok", llm_provider=settings.LLM_PROVIDER, version=settings.APP_VERSION)


@app.on_event("startup")
async def on_startup() -> None:
    """Log the active configuration once at startup, for easy debugging."""
    logger.info(
        "%s v%s starting | environment=%s | llm_provider=%s",
        settings.APP_NAME,
        settings.APP_VERSION,
        settings.ENVIRONMENT,
        settings.LLM_PROVIDER,
    )
